version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:
      rest_api
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=db

volumes:
  data: {}

